# Generated by Django 2.2.4 on 2021-05-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='question',
            field=models.TextField(default='question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(default='question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='question',
            field=models.TextField(default='question'),
            preserve_default=False,
        ),
    ]
