# Generated by Django 2.2.4 on 2021-06-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_homesectionblogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blogs', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='homesectionblogs',
            options={'verbose_name': 'HomeSection Blogs', 'verbose_name_plural': 'HomeSection Blogs'},
        ),
        migrations.AlterModelOptions(
            name='popularblogs',
            options={'verbose_name': 'Popular Blogs', 'verbose_name_plural': 'Popular Blogs'},
        ),
    ]
