# Generated by Django 2.2.4 on 2021-06-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20210605_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogreply',
            options={'ordering': ['-post_date'], 'verbose_name_plural': 'Blog Reply'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Category'},
        ),
        migrations.RemoveField(
            model_name='homesectionblogs',
            name='category',
        ),
        migrations.RemoveField(
            model_name='homesectionblogs',
            name='sub_category',
        ),
    ]
