# Generated by Django 2.1.7 on 2021-06-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20210605_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='home_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
