# Generated by Django 2.1.7 on 2021-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blog_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
